### ISSUE TITLE
Create mock of About pages

### ISSUE THREAD

**Issue by aguro1991** [aguro1991/kidyuki#17]

**Comment by ps2dude756** [comment]
![mobile portrait - nav menu](https://cloud.githubusercontent.com/assets/2060833/26029595/66149a14-37ed-11e7-91f9-7fbf4f05d514.png)

**Comment by aguro1991** [comment]
![about page](https://cloud.githubusercontent.com/assets/2060833/26233367/b48c6d5c-3c11-11e7-9050-2aa19f992ee5.png)
